version: '3.4'
services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
    networks:
      - node-network
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - db

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    restart: always
    networks:
      - node-network
    ports:
      - 8080:80
    depends_on:
      - app

  db:
    build:
      context: .
      dockerfile: .docker/mysql/Dockerfile
    container_name: db
    restart: always
    tty: true
    networks:
      - node-network
    volumes:
      - ./.docker/mysql/volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

volumes:
  node_modules:

networks:
  node-network:
    driver: bridge
